#!bin/sh
clear 

FLAGS="-g -O0 -Wall -Wextra -std=c99 -pedantic"

rm -f *.o #remove hanging object files
rm -f */*.o


# compile all .c files

for i in *.c 
do 
	gcc $FLAGS -c $i
done 

for i in */*.c
do 
	gcc $FLAGS -c $i
done
gcc $FLAGS -o build_solve build_solve.o \
	uarray2.o stack.o mazebuilder.o \
